### ISSUE TITLE
Chrome TLS ERR_SSL_VERSION_INTERFERENCE Error

### ISSUE THREAD

**Issue by dshimy** [webpack/webpack-dev-server#1955]
- Operating System: MacOS 10.14.5
- Node Version: v12.3.1
- NPM Version: 6.9.0
- webpack Version: 4.32.2
- webpack-dev-server Version: 3.5.1
- Chrome: 74.0.3729.169 (latest)

- [x] This is a **bug**
- [ ] This is a **modification** request

### Summary

This issue is limited to Chrome.  Latest stable versions of Firefox and Safari work as expected.  Starting the webpack-dev-server with `https: true` creates a custom cert.  When this cert is installed Chrome (and other browsers) works as expected.  

When I generate a custom cert, an `ERR_SSL_VERSION_INTERFERENCE` error is returned by Chrome.  The cert is added to the MacOS keychain and trusted.

### Config

```yaml
  dev_server:
    https:
      cert: './ssl/localhost.crt'
      key: './ssl/localhost.key'
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'
```

### Expected Behavior

Chrome to load the page without the TLS error.

### Actual Behavior

Chrome returns an `ERR_SSL_VERSION_INTERFERENCE` error.

### For Bugs; How can we reproduce the behavior?

(This is coming via an integration with Rails and Webpacker, hence the yaml config.)

1. Create file `openssl.cnf`:
```
[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no
[req_distinguished_name]
CN = localhost
[v3_req]
keyUsage = keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names
[alt_names]
DNS.1 = localhost
```

2. Generate cert:
```
openssl req -new -newkey rsa:2048 -sha1 -days 3650 -nodes -x509 -keyout localhost.key -out localhost.crt -config openssl.cnf
```
3. Add cert to MacOS Keychain and trust certificate (done via UI).

4. Add config to server.

```yaml
    https:
      cert: './ssl/localhost.crt'
      key: './ssl/localhost.key'
```

5. Test by visiting https://localhost:3035/sockjs-node/info?t=1503127986584 in various browsers.
