### ISSUE TITLE
File is not complied after multiple tries.

### ISSUE THREAD

**Issue by lemingos** [webpack/webpack-dev-server#2353]
- Operating System: Docker on Mac
- Node Version: v11.15.0
- NPM Version: 6.7.0
- webpack Version: 4.41
- webpack-dev-server Version: 3.9.0
- Browser: Chrome

- [x] This is a **bug**

### Code
docker-compose
```
  webpacker:
    image: ${DOCKER_IMAGE_NAME-dockerrailsdemo}
    command: ["./scripts/start_webpack_dev.sh"]
    volumes:
      - .:/opt/dockerrailsdemo:cached
    ports:
      - 3035:3035
```
scripts/start_webpack_dev.sh

```
echo "starting webpack dev" && export NODE_OPTIONS="--max_old_space_size=4096" && yarn && rm -rf /opt/dockerrailsdemo/public/packs && bin/webpack-dev-server
```

### Expected Behavior

I expect to have webpacker-dev-server compiling every time I save the file

### Actual Behavior

Compilation works only for first 3-5 times, then nothing happens on file save. It works properly outside of the docker container.

### For Bugs; How can we reproduce the behavior?

Install https://github.com/soulmates-ai/docker-rails-demo
Run `docker-compose up`
save application.js multiple times, it hangs after few tries.
