### ISSUE TITLE
webpack-dev-server 4 - no support for watchFiles polling - cannot run in docker containers

### ISSUE THREAD

**Issue by trentmurray** [webpack/webpack-dev-server#3483]
- [ X ] This is a **bug**
- [ ] This is a **modification** request

### Code

```
// Dockerfile
FROM node:14.17-stretch-slim

RUN apt-get -y update && apt-get -y install ruby-compass bzip2 git g++ build-essential python3 && apt-get -y dist-upgrade

RUN npm install -g @quasar/cli
COPY ./compose/web/start-server.sh /start-server.sh
RUN sed -i 's/\r//' /start-server.sh
RUN chmod +x /start-server.sh

# Remove the app directory for now if it exists. If running locally, this will be overriden by the bind mount anyway.
RUN rm -rf /app/*
COPY ./compose/web/ /app/

EXPOSE 8080
WORKDIR /app/
```

```bash
// start-server.sh (simplified)

#!/usr/bin/env bash
npm install && quasar dev
exec "$@";

```

```yaml
// docker-compose.yaml 

  ui:
    container_name: ui
    build:
      context: .
      dockerfile: ./compose/web/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./compose/web
        target: /app
    env_file: .env
    command: /start-server.sh

```

```js
// quasar.conf.js v4 (includes webpack config section)
  devServer: {
    https: false,
    port: 8080,
    open: false,
    public: process.env.VUE_APP_DEV_HOST_IP,
    hot: true,
    compress: false,
    watchFiles: [
      'src/**/*', 'public/**/*',
    ],
  },

// quasar.js v3
  devServer: {
    https: false,
    port: 8080,
    open: false,
    public: process.env.VUE_APP_DEV_HOST_IP,
    hot: true,
    compress: false,
    watchOptions: {
        poll: 1000, // every second
    }
  },

```

### Please paste the results of `webpack-cli info` here, and mention other relevant information

Compiles OK, however hot reloading no longer works. No changes are picked up.

### Expected Behavior

There should be an ability to poll the containers host filesystem for changes like there was in v3

### Actual Behavior

Nothing happens when files are changed. No hot reloading, no recompiling.

### For Bugs; How can we reproduce the behavior?

Just any devserver in a docker container, and try to change one of the watched files in your IDE. Nothing happens
