### ISSUE TITLE
Webpacker container dies with side-car mode on k8 Minikube

### ISSUE THREAD

**Issue by ndrean** [webpack/webpack-dev-server#3716]
- [x ] This is a **bug**
- [ ] This is a **modification** request

### Code

k8s manifest running side-car Rails server and Webpack-dev-server from the same image
```yml
containers:
    - name: frontend
       image: builder-dev
      command: ["./bin/webpack-dev-server"]
      ports:
         - containerPort: 3035
      env:
        - name: WEBPACKER_DEV_SERVER_HOST
              value: "0.0.0.0"
   - name: backend
      image: builder-dev
     command: ["bundle"]
     args: ["exec", "rails", "server", "-b", "0.0.0.0"]
     ports:
       - containerPort: 3000
     env:
      - name: WEBPACKER_DEV_SERVER_HOST
              value: "frontend"
```

### Please paste the results of `webpack-cli info` and `webpack-cli version` here, and mention other relevant information

`webpack-cli info`
Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: 3b01ec2c03ba3406acc4
Version: webpack 4.46.0
Time: 74ms
Built at: 08/22/2021 12:18:59 AM

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in Entry module not found: Error: Can't resolve 'version' in '/Users/utilisateur/Exercism/K8/docker-slim'

`webpack-cli version`
Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: 3b01ec2c03ba3406acc4
Version: webpack 4.46.0
Time: 75ms
Built at: 08/22/2021 12:18:47 AM

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
### Expected Behavior
You should be able to run a standalone webpacker-de-server aside a Rails container in a k8 pod to enable HMR.

### Actual Behavior
The webpacker-dev-server container dies quickly without serving or compiling the assets.

```yml
default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  webpack_compile_output: true
development:
  <<: *default
  compile: true
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
   ...
```

```rb
RAILS_SERVE_STATIC_FILES=true
```
All the assets are in "/javascript/images/",  declared in  "app/javacsript/packs/applications.js":
```js
const images = require.context("../images", true);
const imagePath = (name) => images(name, true);
```
I build a standard Rails image. On a Minikube cluster, I run in the same pod Rails and Webpacker.
```sh
[backend] => Run `bin/rails server --help` for more startup options
[frontend] ℹ ｢wds｣: Project is running at http://localhost:3035/
[frontend] ℹ ｢wds｣: webpack output is served from /packs/
[frontend] ℹ ｢wds｣: Content not from webpack is served from /app/public/packs
[frontend] ℹ ｢wds｣: 404s will fallback to /index.html
[backend] Puma starting in single mode...
...
[backend] [Webpacker] Compiling...
```

The Webpacker container **dies quickl**  when running side-car to Rails in a pod within a Minikube cluster. The static assets are not rendered correctly.

The [frontend] dies and the [backend] responds:
```sh
[backend] [Webpacker] Everything's up-to-date. Nothing to do
```

The **same**  code, **same** image runs (poorly) when Rails is alone in the pod. Runs mean I can display the assets (poorly) but  not the React code.

If I add the compilation in the image,  `RUN bundle exec rails webpacker:compile assets:clean` , then Rails alone displays everything correctly with `[Webpacker] Everything's up-to-date. Nothing to do`. but no HMR. You have to rebuild the image on changes.

Error:
Detected container restart. Pod: rails-dep-54446d8b4f-7pz74. Container: backend.

When using docker-compose with both services, Rails and Webpacker, which works like a charm with the same config.

### For Bugs; How can we reproduce the behaviour?

Within a Minikube cluster, add in a pod a Rails app and a Webpacker service.
